apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-chol
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-chol
    app.kubernetes.io/part-of: test-app-uxux
  name: docker-devfile-sample-hello-world-chol
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-devfile-sample-hello-world-chol
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-devfile-sample-hello-world-chol
    spec:
      containers:
      - image: quay.io/ysubrama_org/build-e2e-gakv-tenant/test-app-uxux/docker-devfile-sample-hello-world-chol@sha256:27cc88b13a92356fbe7f0d6a27d15829d5619f5aca45bb4c82aa1c4148b21607
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
